CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y

### NICE OLED CONFIGURATION (Right Half)
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL=n
CONFIG_NICE_OLED_WIDGET_STATIC_IMAGE_PERIPHERAL=n
CONFIG_NICE_OLED_WIDGET_STATIC_IMAGE_PERIPHERAL_GUGUINHATOP=n
CONFIG_NICE_OLED_WIDGET_RIGHT_HUD=y
CONFIG_ZMK_SPLIT_PERIPHERAL_HID_INDICATORS=y
CONFIG_NICE_OLED_WIDGET_REACTIVE_RGB=y
CONFIG_BT_MAX_CONN=3
CONFIG_BT_MAX_PAIRED=3
