### POWER CONFIGURATION
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_EXT_POWER=y
CONFIG_ZMK_IDLE_TIMEOUT=600000
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

### DISPLAY CONFIGURATION
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_BLANK_ON_IDLE=y
CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y
CONFIG_ZMK_DISPLAY_DEDICATED_THREAD_PRIORITY=10
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y

### NICE OLED CONFIGURATION
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL=n
CONFIG_NICE_OLED_WIDGET_STATIC_IMAGE_PERIPHERAL=y 
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_CAT=n

### LIGHTING CONFIGURATION
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_WS2812_STRIP=y
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=y
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_USB=y
CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=3

### ENCODER CONFIGURATION
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_OWN_THREAD=y
CONFIG_EC11_THREAD_PRIORITY=2

### KEYBOARD SCAN CONFIGURATION
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=1
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5

### BLUETOOTH CONFIGURATION
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y
CONFIG_BT_PERIPHERAL_PREF_MIN_INT=6
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=6
CONFIG_BT_PERIPHERAL_PREF_LATENCY=30
CONFIG_ZMK_SPLIT_BLE_PREF_INT=6
CONFIG_ZMK_SPLIT_BLE_PREF_LATENCY=30
CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=n
